const fabledRoles = [
            {
                "id": "doomsayerCustomVER",
                "name": "末日预言者",
                "pinyin": "moriyuyanzhe",
                "pinyinsuoxie": "mryyz",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/19_image3.png",
                "ability": "如果大于等于四名玩家存活，每名当前存活的玩家可以公开要求你杀死一名与他阵营相同的玩家（每名玩家限一次）。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "而在第七天，洪水和瘟疫将席卷渡鸦村！死者终会复活，生者将遭挫折！哦！真是天灾人祸啊！哦！真是不幸的一天！只有付出巨大的牺牲才能熬过这一切！诺斯特罗斯的贤者是这么说的，我也是这么说的。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "angelCustomVER",
                "name": "天使",
                "pinyin": "tianshi",
                "pinyinsuoxie": "ts",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/21_image3.png",
                "ability": "对新玩家的死亡负最大责任的人，可能会遭遇一些不好的事情。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "让无罪之人勇于向我所选之人举起手，因为成倍的风暴之怒以及正义终会降临在这群傻瓜身上。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["庇护","不好的事"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "buddhistCustomVER",
                "name": "佛教徒",
                "pinyin": "fojiaotu",
                "pinyinsuoxie": "fjt",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/22_image3.png",
                "ability": "每个白天的前两分钟老玩家不能发言。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "人生在世如身处荆棘之中，心不动，人不妄动，不动则不伤。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "hellslibrarianCustomVER",
                "name": "地狱图书管理员",
                "pinyin": "diyutushuguanlibian",
                "pinyinsuoxie": "dytsglb",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/24_image3.png",
                "ability": "当说书人宣布安静时，仍在说话的玩家可能会遭遇一些不好的事情。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "嘘……请安静。最好不要打扰到藏书员，我知道他脾气可不小。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["不好的事","不好的事","不好的事","不好的事","不好的事"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "revolutionaryCustomVER",
                "name": "革命者",
                "pinyin": "gemingzhe",
                "pinyinsuoxie": "gmz",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/23_image3.png",
                "ability": "公开声明一对邻座玩家本局游戏一直保持同一阵营。每局游戏限一次，他们中的一人可能被当作其他的角色/阵营。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "团结，假装的。分裂，就拖延。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["被当作其他","被当作其他"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "fiddlerCustomVER",
                "name": "小提琴手",
                "pinyin": "xiaotiqinshou",
                "pinyinsuoxie": "xtqs",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/25_image3.png",
                "ability": "每局游戏限一次，恶魔可以秘密选择一名对立阵营的玩家，所有玩家要表决：这两名玩家中谁的阵营获胜。（平局邪恶阵营获胜）",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "我敢用命打赌你在小提琴比赛中肯定赢不了我，你这个独眼的呆子！我们之后再一起出去好好地喝上一杯，享受酒吧里的绝伦美曲，沉浸其中，直到隔天醒来连为什么我的鞋子会套在你的脚上都不知道。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "toymakerCustomVER",
                "name": "玩具匠",
                "pinyin": "wanjujiang",
                "pinyinsuoxie": "wjj",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/20_image3.png",
                "ability": "恶魔可以在夜晚选择放弃攻击（每局游戏至少一次）。邪恶玩家照常获取初始信息。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 110,
                "team": "fabled",
                "edition": "custom",
                "flavor": "它会发出声音！会自己下楼！还可以在夜里为你提供温暖！它尝起来像糖果！孩子们都喜欢它！隆重介绍...这就是全新的 温暖的-巴兹-乌兹-行走机器人装置！适合全年龄段！",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["无法攻击"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "fibbinCustomVER",
                "name": "骗人精",
                "pinyin": "pianrenjing",
                "pinyinsuoxie": "prj",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/26_image3.png",
                "ability": "每局游戏限一次，一名善良玩家可能会得知“有问题”的信息。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "嘻嘻嘻，哈，嘻嘻。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["失去能力"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "duchessCustomVER",
                "name": "公爵夫人",
                "pinyin": "gongjuefuren",
                "pinyinsuoxie": "gjfr",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/27_image3.png",
                "ability": "每个白天，三名玩家可以一起拜访你。当晚*，他们会得知他们之中有几个是邪恶的，但其中一人的信息是错的。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 150,
                "team": "fabled",
                "edition": "custom",
                "flavor": "我们会在6点至7点之间招待客人。6点15分喝茶点。6点45分吃松饼。不要迟到，着装要像往常一样正式。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["访客","访客","访客","错误信息"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "sentinelCustomVER",
                "name": "哨兵",
                "pinyin": "shaobing",
                "pinyinsuoxie": "sb",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/28_image3.png",
                "ability": "在初始设置时，可能会额外增加或减少一个外来者。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "请提供你的名字，请出示你的证件，请展示你的武器。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "spiritofivoryCustomVER",
                "name": "圣洁之魂",
                "pinyin": "shengjiezhihun",
                "pinyinsuoxie": "sjzh",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/29_image3.png",
                "ability": "游戏过程中邪恶玩家的总数最多能比初始设置多一名。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "荒芜之地传来呼唤，生肉枯骨，落入尘土。是圣洁之魂在生长，是圣洁之魂在注视，是圣洁之魂在引导。人类遵循这一切，否则早已被覆灭。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["禁止邪恶"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "djinnCustomVER",
                "name": "灯神",
                "pinyin": "dengshen",
                "pinyinsuoxie": "ds",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/30_image3.png",
                "ability": "使用灯神的相克规则。所有玩家都会知道其内容。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "我们并非在此，你也未必真实，一切神秘皆是幻象难觅，茫茫问题好似晴天霹雳。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "ferrymanCustomVER",
                "name": "摆渡人",
                "pinyin": "baiduren",
                "pinyinsuoxie": "bdr",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/32_image3.png",
                "ability": "在游戏的最后一天，所有已死亡玩家会重新获得投票标记。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "当正义的梦想到来之时，它会带着真理的重量。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "deusexfiascoCustomVER",
                "name": "失败的上帝",
                "pinyin": "shibaideshangdi",
                "pinyinsuoxie": "sbdsd",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/31_image3.png",
                "ability": "每局游戏至少一次，说书人将会出现失误，但会纠正并公开承认自己曾处理有误。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "这不是漏洞，是神迹。这不是失误，是天意。这不是崩坏，是风格。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["哎呀！"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "qilinCustomVER",
                "name": "麒麟",
                "pinyin": "qilin",
                "pinyinsuoxie": "ql",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/33_image3.png",
                "ability": "在游戏的最后一天，最幸运的玩家身上会发生一些好的事情。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "麟之趾，振振公子，于嗟麟兮！麟之定，振振公姓，于嗟麟兮！麟之角，振振公族，于嗟麟兮！",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["好的事情"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "shelingchengzhiCustomVER",
                "name": "赦令承旨",
                "pinyin": "shelingchengzhi",
                "pinyinsuoxie": "slcz",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/44_image3.png",
                "ability": "解除所有角色能力在进行选择时的限制条件。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "奉天承运，皇帝诏曰：大赦天下。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": false
            },

            {
                "id": "stormcatcherCustomVER",
                "name": "暴风捕手-奇遇",
                "pinyin": "baofengbushou",
                "pinyinsuoxie": "bfbs",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/34_image3.png",
                "ability": "游戏开始时，你要宣布一个善良角色。如果该角色在场，他只能死于处决，但所有邪恶玩家会在首个夜晚得知他是哪一名玩家。",
                "scripts": ["传奇角色"],
                "firstNight": 110,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "在黎明时分，庙宇那被拉长的影子爬上了泉眼。而在黄昏时分，方尖塔将刺目的红光遮挡，让拱道下方的暖流冷却。所有的线索都汇聚于此。风暴将至，而在这苹果树之间，这耀眼、葱翠又圣洁的地方，定是那暴风眼。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["不会死亡","不会死亡","不会死亡"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "Ventriloquist",
                "name": "腹语师-奇遇",
                "pinyin": "fuyushi",
                "pinyinsuoxie": "fys",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/35_image3.png",
                "ability": "如果一名玩家在被提名时‘疯狂’地证明自己是一个新的角色，他可能不会死于当天的处决。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "来来来，各位看官都围过来！这是我的老搭档查理，他那张嘴啊，能把驴都说羞了。不过别担心，各位——开口说话的一直是我……对吧？",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["不会死亡","疯狂"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "Pope",
                "name": "教皇-奇遇",
                "pinyin": "jiaohuang",
                "pinyinsuoxie": "jh",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/36_image3.png",
                "ability": "会有重复的善良角色在场。他们也可能是恶魔的伪装。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "……至美之名。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["重复"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "bigwigCustomVER",
                "name": "首席律师-奇遇",
                "pinyin": "shouxilvshi",
                "pinyinsuoxie": "sxls",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/37_image3.png",
                "ability": "每个被提名者要选择一名玩家：在投票前，只有他可以发言，并且他要“疯狂”地证明被提名者是善良的，否则他可能死亡。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "虚荣会问：'这受欢迎吗？'懦弱会问：'这安全吗？'良知会问：'这对吗？'那我们之中，谁敢问一句：'这是真的吗？'",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "bootleggerCustomVER",
                "name": "私货商人-奇遇",
                "pinyin": "sihuoshangren",
                "pinyinsuoxie": "shsr",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/38_image3.png",
                "ability": "这个剧本包含有自制角色或自制规则。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "~~~待补充~~~",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "hinduCustomVER",
                "name": "印度教教徒-奇遇",
                "pinyin": "yindujiaojiaotu",
                "pinyinsuoxie": "ydjjt",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/39_image3.png",
                "ability": "最先死亡的四名玩家会立刻以相同阵营的旅行者转世重生。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "“四者陨落于生灭之隙，”“四者归返于流转之途。”“四者心住于道法，”“四者不复终结于终。”（印度语）",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": false
            },
             {
                "id": "hinduCustomVER",
                "name": "诡诈杰克-奇遇",
                "pinyin": "guizhajieke",
                "pinyinsuoxie": "gzjk",
                "image": "https://www.bloodstar.xyz/p/shifenfantuan/jiuban/newcharacter1_jiuban.png",
                "ability": "场上有两位说书人：一人说真话，一人说假话。每局游戏限一次，他们可能会在黄昏互换。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "处处皆可为门，餐餐皆可为宴。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": false
            },
                         {
                "id": "hinduCustomVER",
                "name": "讷神-奇遇",
                "pinyin": "nashen",
                "pinyinsuoxie": "ns",
                "image": "https://www.bloodstar.xyz/p/shifenfantuan/jiuban/newcharacter2_jiuban.png",
                "ability": "会有一顶讷帽。当玩家戴着讷帽的时候，只能说单音节词，但投票算作两票。如果违反规则，讷帽会被转移。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "我的孩子们是被祝福的，因为他们能在简单之物之中看见美。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "zenomancerCustomVER",
                "name": "异术士-奇遇",
                "pinyin": "yishushi",
                "pinyinsuoxie": "yss",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/40_image3.png",
                "ability": "一名或多名玩家各自拥有一个目标。当达成目标后，他会获得一条正确信息。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "有人说，宇宙是动态的，而非静止，这一切都承载于驮着巨龟的巨龟之上，层层叠叠的巨龟，我的朋友，永无止境。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["目标","目标","目标"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "torCustomVER",
                "name": "遗忘之门-奇遇",
                "pinyin": "yiwangzhimen",
                "pinyinsuoxie": "ywzm",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/41_image3.png",
                "ability": "玩家不知道自己的角色和阵营。当他们死亡时才会得知这些信息。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "雷鸣是我的言语，闪电是我的剑。我是永恒的守门者，吞噬一切妄闯禁域的愚者。我的圣志昭然：净化尘世的污虫，将其困缚于星光织成的网中，在那天与地交汇的山巅，守望永恒的真理。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": true
            },
            {
                "id": "gardenerCustomVER",
                "name": "园丁-奇遇",
                "pinyin": "yuanding",
                "pinyinsuoxie": "yd",
                "image": "https://www.bloodstar.xyz/p/Haimian0421/image3/42_image3.png",
                "ability": "由说书人来为一名或更多玩家派发角色。",
                "scripts": ["传奇角色"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "fabled",
                "edition": "custom",
                "flavor": "~~~待补充~~~",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": false
            }
        ];