const travellersRoles = [

            {
                "id": "bureaucratCustomVER",
                "name": "官员",
                "pinyin": "guanyuan",
                "pinyinsuoxie": "gy",
                "image": "images/bureaucrat.png",
                "ability": "每个夜晚，你要选择除你以外的一名玩家：明天白天，他的投票算作三票。",
                "scripts": ["旅行者"],
                "firstNight": 120,
                "otherNight": 120,
                "team": "traveller",
                "edition": "custom",
                "flavor": "请在这签名，还有这里，还有这，还...有这。如果每个人的签名都清晰可辨，在今天就应该可以把所有文件都整理统计好。这种简单的文书工作，我们已经很久没犯错了。从昨天中午到现在都没有，如果没记错的话……",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["3票"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "beggarCustomVER",
                "name": "乞丐",
                "pinyin": "qigai",
                "pinyinsuoxie": "qg",
                "image": "images/beggar.png",
                "ability": "你只能使用投票标记才能投票。死亡的玩家可以将他的投票标记给你，如果他这么做，你会得知他的阵营。你不会中毒和醉酒。",
                "scripts": ["旅行者"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "traveller",
                "edition": "custom",
                "flavor": "行行好吧，先生？哪怕是一枚硬币，夫人？谢天谢地，上天保佑！你真是个善良的人！今晚我要好好地吃上一顿，一定要！",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "gunslingerCustomVER",
                "name": "枪手",
                "pinyin": "qiangshou",
                "pinyinsuoxie": "qs",
                "image": "images/gunslinger.png",
                "ability": "每个白天，当首次投票被统计后，你可以选择一名刚投过票的玩家：他死亡。",
                "scripts": ["旅行者"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "traveller",
                "edition": "custom",
                "flavor": "是时候得有人自己动手了。那个人...就是我。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "thiefCustomVER",
                "name": "窃贼",
                "pinyin": "qiezei",
                "pinyinsuoxie": "qz",
                "image": "images/thief.png",
                "ability": "每个夜晚，你要选择除你以外的一名玩家：明天白天他的投票会被算作负数。",
                "scripts": ["旅行者"],
                "firstNight": 125,
                "otherNight": 125,
                "team": "traveller",
                "edition": "custom",
                "flavor": "我可是嘛事儿也没干。昨儿嘛晚我连内个小巷子都没去过！绝不是我偷了布鲁诺镇长的公文包。它内包儿里面儿讷么老些花哨儿纸儿，可太沉了。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["负票"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "scapegoatCustomVER",
                "name": "替罪羊",
                "pinyin": "tizuiyang",
                "pinyinsuoxie": "tzy",
                "image": "images/scapegoat.png",
                "ability": "如果你的阵营的一名玩家被处决，你可能会代替他被处决。",
                "scripts": ["旅行者"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "traveller",
                "edition": "custom",
                "flavor": "晚上好！感谢你们邀请我来舞厅。虽然我不是本地人，但你们看起来个个都慈眉善目的，我的天呐。我相信我们一定可以打成一片的。不过这些绳子是干嘛的？",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "judgeCustomVER",
                "name": "法官",
                "pinyin": "faguan",
                "pinyinsuoxie": "fg",
                "image": "images/judge.png",
                "ability": "每局游戏限一次，如果其他玩家发起了提名，你可以选择让本次提名直接执行处决或让投票无效。",
                "scripts": ["旅行者"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "traveller",
                "edition": "custom",
                "flavor": "我认为被告人涉嫌谋杀罪、诈骗罪、放火罪、盗窃罪、招摇撞骗罪、非法行医罪、诽谤罪、弑君罪以及乱丢垃圾罪等罪行。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["失去能力"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "matronCustomVER",
                "name": "女舍监",
                "pinyin": "nvshejian",
                "pinyinsuoxie": "nsj",
                "image": "images/matron.png",
                "ability": "每个白天，你可以选择至多三对玩家交换座位。玩家不能离开座位私聊。",
                "scripts": ["旅行者"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "traveller",
                "edition": "custom",
                "flavor": "费瑟伯顿小姐，你能不能安静点。卢瑟福少爷，请只用四根手指端起茶杯。我知道你是九个孩子的父亲，但无论是年龄还是其他什么原因，都不能成为你没礼貌的借口。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "voudonCustomVER",
                "name": "巫毒师",
                "pinyin": "wudushi",
                "pinyinsuoxie": "wds",
                "image": "images/voudon.png",
                "ability": "只有你和死亡的玩家可以投票，且投票不需要使用投票标记。忽略票数需要过半的要求。",
                "scripts": ["旅行者"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "traveller",
                "edition": "custom",
                "flavor": "欢迎。先坐下来，深呼吸。进入活死人之地，以他眼视之，以他声言之。借万灵之音。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "apprenticeCustomVER",
                "name": "学徒",
                "pinyin": "xuetu",
                "pinyinsuoxie": "xt",
                "image": "images/apprentice.png",
                "ability": "在你的首个夜晚，如果你是善良的，你会获得一个镇民角色的能力；如果你是邪恶的，你会获得一个爪牙角色的能力。",
                "scripts": ["旅行者"],
                "firstNight": 130,
                "otherNight": 130,
                "team": "traveller",
                "edition": "custom",
                "flavor": "这么多年来，我一路上不停地在学习各种各样的手艺。你问我学的是什么手艺？简单说都是一些普通的手艺，没什么好担心的，至少现在不必。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["是学徒"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "bishopCustomVER",
                "name": "主教",
                "pinyin": "zhuojiao",
                "pinyinsuoxie": "zj",
                "image": "images/bishop.png",
                "ability": "只有说书人可以发起提名。每个白天说书人至少要提名一名你对立阵营的玩家。",
                "scripts": ["旅行者"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "traveller",
                "edition": "custom",
                "flavor": "我以圣父，圣子，圣灵的名义...乞求主神保佑我们。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["提名善良方","提名邪恶方"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "deviantCustomVER",
                "name": "怪咖",
                "pinyin": "guaika",
                "pinyinsuoxie": "gk",
                "image": "images/deviant.png",
                "ability": "如果你表现得很有趣，当天你不能被流放。",
                "scripts": ["旅行者"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "traveller",
                "edition": "custom",
                "flavor": "这句好笑的话确实是那位女士说的。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "bone_collectorCustomVER",
                "name": "集骨者",
                "pinyin": "jiguzhe",
                "pinyinsuoxie": "jgz",
                "image": "images/bone_collector.png",
                "ability": "每局游戏限一次，在夜晚时*，你可以选择一名死亡的玩家：他重新获得能力直到下个黄昏。",
                "scripts": ["旅行者"],
                "firstNight": 0,
                "otherNight": 145,
                "team": "traveller",
                "edition": "custom",
                "flavor": "我收集了很多东西。头发、牙齿、衣服、诗歌片段以及失散恋人的美梦。还有我的秘密艺术品，你想看的话那可得给点小费，一点点就可以。如果你能给我带来一些月圆之夜死于悲痛的贵妇人的血，你就会得到你想要的答案。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["重获能力","失去能力"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "baristaCustomVER",
                "name": "咖啡师",
                "pinyin": "kafeishi",
                "pinyinsuoxie": "kfs",
                "image": "images/barista.png",
                "ability": "每个夜晚，直至下个黄昏，由说书人二选一：1）一名玩家解除并免受醉酒和中毒影响，且会得知正确信息；2）一名玩家的能力可以生效两次。该玩家会得知是哪个效果。",
                "scripts": ["旅行者"],
                "firstNight": 135,
                "otherNight": 135,
                "team": "traveller",
                "edition": "custom",
                "flavor": "一杯不加奶油的咖啡，先生？我真的很抱歉，我们刚刚用完了所有的奶油——一杯不加牛奶的咖啡怎样？",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["清醒且健康","行动两次"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "harlotCustomVER",
                "name": "流莺",
                "pinyin": "liuying",
                "pinyinsuoxie": "ly",
                "image": "images/harlot.png",
                "ability": "每个夜晚*，你要选择一名存活的玩家：如果他同意，你会得知他的角色，但是你们两个可能同时死亡。",
                "scripts": ["旅行者"],
                "firstNight": 0,
                "otherNight": 140,
                "team": "traveller",
                "edition": "custom",
                "flavor": "认得侬老开心额，水手。你好像有些烦心事想告诉我，对嘛对嘛，而我就是一个很棒棒的聆听者。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["死亡","死亡"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "butcherCustomVER",
                "name": "屠夫",
                "pinyin": "tufu",
                "pinyinsuoxie": "tf",
                "image": "images/butcher.png",
                "ability": "每个白天，首次处决后，你可以再次发起提名。",
                "scripts": ["旅行者"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "traveller",
                "edition": "custom",
                "flavor": "这口感好像鸡肉..……请再来一份。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "gangsterCustomVER",
                "name": "黑帮",
                "pinyin": "heibang",
                "pinyinsuoxie": "hb",
                "image": "images/gangster.png",
                "ability": "每个白天限一次，你可以杀死与你邻近的两名存活的玩家中的一名，但需要另一边那个存活的玩家同意。",
                "scripts": ["旅行者"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "traveller",
                "edition": "custom",
                "flavor": "我喜欢你的鞋子。不过要是你遭遇了什么小小的意外，不小心弄坏了它们，那可就丢人了。既然你提到了，其实我也挺喜欢你的袖扣的。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "gnomeCustomVER",
                "name": "侏儒",
                "pinyin": "zhuru",
                "pinyinsuoxie": "zr",
                "image": "images/gnome.png",
                "ability": "当你加入游戏时，所有玩家会得知一名与你阵营相同的玩家。每当他被提名时，你可以杀死提名者。",
                "scripts": ["旅行者"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "traveller",
                "edition": "custom",
                "flavor": "有备而来，有悲而来，无人搭台，自己开嗨！一场整人好戏，整得人惨兮兮，吱吱作响板板，又怕翻了盘盘。那些长篇大论顺着乔伊斯的溪流在流淌，不算最辉煌，也还够气场，却也挺像样——哈，响亮！",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["同伴"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "diaominCustomVER",
                "name": "刁民",
                "pinyin": "diaomin",
                "pinyinsuoxie": "dm",
                "image": "images/diaomin.png",
                "ability": "曾在白天粗暴地打断过你的发言的玩家之一会在当晚醉酒，即使你已死亡。",
                "scripts": ["旅行者"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "traveller",
                "edition": "custom",
                "flavor": "~~~待补充~~~",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["醉酒"],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "jiaohuaziCustomVER",
                "name": "叫花子",
                "pinyin": "jiaohuazi",
                "pinyinsuoxie": "jhz",
                "image": "images/jiaohuazi.png",
                "ability": "每个白天限一次，你可以公开选择一名其他玩家，让他选择一个非恶魔角色：你可能会获得这个角色的能力，直到下个黎明。",
                "scripts": ["旅行者"],
                "firstNight": 0,
                "otherNight": 0,
                "team": "traveller",
                "edition": "custom",
                "flavor": "瞧一瞧，看一看，这里来个穷要饭。给个馍，给口汤，祝恁长命又健康。行行好，行行妙，施舍得人呱呱叫。让额走，额就走，⽼板伸出富贵⼿。",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": [],
                "remindersGlobal": [],
                "setup": false
            },
            {
                "id": "cacklejackCustomVER",
                "name": "笑匠",
                "pinyin": "xiaojiang",
                "pinyinsuoxie": "xj",
                "image": "images/cacklejack.png",
                "ability": "每个白天，你要选择一名玩家，当晚另一名玩家的角色会改变。",
                "scripts": ["旅行者"],
                "firstNight": 0,
                "otherNight": 118,
                "team": "traveller",
                "edition": "custom",
                "flavor": "Wire α To wire β. LigHt oN. BuZZer off. GAzOinks! Arms STra1ght. FingER 2 nose. hOooLd stiLL. BoiNgo-banGo! Ha-ha-ha!",
                "jinxes": [],
                "special": [],
                "firstNightReminder": "",
                "otherNightReminder": "",
                "reminders": ["NotMe不变"],
                "remindersGlobal": [],
                "setup": false
            }
        ];